import type { BountyTier, TradeDirection, TradingAsset } from "@/types";

export interface BountyTemplate {
  id: string;
  tier: BountyTier;
  weight: number;

  titleTemplate: string;
  descriptionTemplate: string;

  asset: TradingAsset;
  direction: TradeDirection | null;
  min_pnl_percent: number | null;
  max_pnl_percent: number | null;
  min_leverage: number | null;
  max_leverage: number | null;
  max_duration_minutes: number | null;
  min_position_size_usd: number;

  ttl_minutes: number;
  reward_points: number;
}

// Weight distribution by tier:
//   15 common × 10 = 150  (76.9%)
//   10 rare   × 4  =  40  (20.5%)
//    5 legendary × 1 =  5  ( 2.6%)
//   total                  195

export const BOUNTY_TEMPLATES: BountyTemplate[] = [
  // ─────────────────── Common (weight 10 each) ───────────────────
  {
    id: "c-sol-flip",
    tier: "common",
    weight: 10,
    titleTemplate: "Quick flip: {asset}",
    descriptionTemplate:
      "Open a {asset} position {direction} and close with at least {minPnl}% profit within {maxDuration} minutes.",
    asset: "SOL",
    direction: null,
    min_pnl_percent: 0.5,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 120,
    reward_points: 50,
  },
  {
    id: "c-sol-momentum-long",
    tier: "common",
    weight: 10,
    titleTemplate: "Momentum long: {asset}",
    descriptionTemplate:
      "Ride a {asset} long to {minPnl}% profit inside the {maxDuration}-minute window.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 50,
    ttl_minutes: 180,
    reward_points: 75,
  },
  {
    id: "c-sol-short-snipe",
    tier: "common",
    weight: 10,
    titleTemplate: "Short snipe: {asset}",
    descriptionTemplate:
      "Close a {asset} short at {minPnl}% or better within {maxDuration} minutes.",
    asset: "SOL",
    direction: "SHORT",
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 120,
    reward_points: 70,
  },
  {
    id: "c-sol-hold",
    tier: "common",
    weight: 10,
    titleTemplate: "Patient hold: {asset}",
    descriptionTemplate:
      "Hold a {asset} long for up to {maxDuration} minutes, close at {minPnl}%+ profit.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 1.5,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 50,
    ttl_minutes: 240,
    reward_points: 90,
  },
  {
    id: "c-sol-any-way",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} starter",
    descriptionTemplate:
      "Any direction, any timeframe — just close a {asset} trade with {minPnl}%+ profit.",
    asset: "SOL",
    direction: null,
    min_pnl_percent: 0.5,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: null,
    min_position_size_usd: 50,
    ttl_minutes: 180,
    reward_points: 30,
  },
  {
    id: "c-btc-scalp",
    tier: "common",
    weight: 10,
    titleTemplate: "BTC scalp",
    descriptionTemplate:
      "Open and close a {asset} trade with {minPnl}%+ profit in under {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 0.5,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 15,
    min_position_size_usd: 50,
    ttl_minutes: 60,
    reward_points: 60,
  },
  {
    id: "c-btc-steady-long",
    tier: "common",
    weight: 10,
    titleTemplate: "Steady long: {asset}",
    descriptionTemplate:
      "Take a {asset} long to {minPnl}%+ profit inside the {maxDuration}-minute window.",
    asset: "BTC",
    direction: "LONG",
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 50,
    ttl_minutes: 180,
    reward_points: 80,
  },
  {
    id: "c-btc-short-squeeze",
    tier: "common",
    weight: 10,
    titleTemplate: "Short squeeze: {asset}",
    descriptionTemplate:
      "Close a profitable {asset} short ({minPnl}%+) within {maxDuration} minutes.",
    asset: "BTC",
    direction: "SHORT",
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 120,
    reward_points: 75,
  },
  {
    id: "c-btc-3x-grind",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} 3x grind",
    descriptionTemplate:
      "Trade {asset} at 3x-5x leverage and close with {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: 3,
    max_leverage: 5,
    max_duration_minutes: 60,
    min_position_size_usd: 100,
    ttl_minutes: 240,
    reward_points: 100,
  },
  {
    id: "c-btc-any-way",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} starter",
    descriptionTemplate:
      "Any direction, any leverage — close a {asset} trade with {minPnl}%+ profit.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 0.5,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: null,
    min_position_size_usd: 50,
    ttl_minutes: 180,
    reward_points: 30,
  },
  {
    id: "c-bonk-fade",
    tier: "common",
    weight: 10,
    titleTemplate: "Quick fade: {asset}",
    descriptionTemplate:
      "Catch a {asset} move in either direction, close at {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 2,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 15,
    min_position_size_usd: 50,
    ttl_minutes: 60,
    reward_points: 50,
  },
  {
    id: "c-bonk-degen-long",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} degen long",
    descriptionTemplate:
      "Long {asset} and close at {minPnl}%+ profit inside {maxDuration} minutes.",
    asset: "BONK",
    direction: "LONG",
    min_pnl_percent: 3,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 120,
    reward_points: 80,
  },
  {
    id: "c-bonk-volatility-ride",
    tier: "common",
    weight: 10,
    titleTemplate: "Volatility ride: {asset}",
    descriptionTemplate:
      "Close a {asset} trade in the {minPnl}-{maxPnl}% profit band within {maxDuration} minutes.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 2,
    max_pnl_percent: 5,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 90,
    reward_points: 60,
  },
  {
    id: "c-bonk-any-way",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} starter",
    descriptionTemplate:
      "Any direction, any leverage — close a {asset} trade with {minPnl}%+ profit.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 1,
    max_pnl_percent: null,
    min_leverage: null,
    max_leverage: null,
    max_duration_minutes: null,
    min_position_size_usd: 50,
    ttl_minutes: 180,
    reward_points: 25,
  },
  {
    id: "c-sol-2x-basics",
    tier: "common",
    weight: 10,
    titleTemplate: "{asset} 2x basics",
    descriptionTemplate:
      "Trade {asset} at 2x+ leverage and close with {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "SOL",
    direction: null,
    min_pnl_percent: 0.5,
    max_pnl_percent: null,
    min_leverage: 2,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 50,
    ttl_minutes: 120,
    reward_points: 60,
  },

  // ─────────────────── Rare (weight 4 each) ───────────────────
  {
    id: "r-sol-precision-long",
    tier: "rare",
    weight: 4,
    titleTemplate: "Precision long: {asset}",
    descriptionTemplate:
      "Open a {asset} long at {minLeverage}x-{maxLeverage}x leverage and close in the {minPnl}-{maxPnl}% profit band within {maxDuration} minutes.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 2,
    max_pnl_percent: 5,
    min_leverage: 5,
    max_leverage: 10,
    max_duration_minutes: 60,
    min_position_size_usd: 200,
    ttl_minutes: 360,
    reward_points: 250,
  },
  {
    id: "r-btc-mid-strike",
    tier: "rare",
    weight: 4,
    titleTemplate: "Mid-leverage strike: {asset}",
    descriptionTemplate:
      "Trade {asset} at {minLeverage}x+ leverage and close with {minPnl}%+ profit inside {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 3,
    max_pnl_percent: null,
    min_leverage: 10,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 200,
    ttl_minutes: 480,
    reward_points: 350,
  },
  {
    id: "r-bonk-volatility-hunter",
    tier: "rare",
    weight: 4,
    titleTemplate: "Volatility hunter: {asset}",
    descriptionTemplate:
      "{asset} at {minLeverage}x+ leverage, close with {minPnl}%+ profit in {maxDuration} minutes or less.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 5,
    max_pnl_percent: null,
    min_leverage: 5,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 100,
    ttl_minutes: 240,
    reward_points: 400,
  },
  {
    id: "r-sol-short-squeeze",
    tier: "rare",
    weight: 4,
    titleTemplate: "Short squeeze: {asset}",
    descriptionTemplate:
      "Open a {asset} short at {minLeverage}x+ and close with {minPnl}%+ profit within {maxDuration} minutes.",
    asset: "SOL",
    direction: "SHORT",
    min_pnl_percent: 3,
    max_pnl_percent: null,
    min_leverage: 10,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 200,
    ttl_minutes: 360,
    reward_points: 300,
  },
  {
    id: "r-btc-scalp-precision",
    tier: "rare",
    weight: 4,
    titleTemplate: "Scalp precision: {asset}",
    descriptionTemplate:
      "Close a {asset} trade in the {minPnl}-{maxPnl}% window at {minLeverage}x+ leverage within {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 2,
    max_pnl_percent: 3,
    min_leverage: 5,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 200,
    ttl_minutes: 360,
    reward_points: 350,
  },
  {
    id: "r-sol-high-conviction",
    tier: "rare",
    weight: 4,
    titleTemplate: "High conviction: {asset}",
    descriptionTemplate:
      "{asset} long at {minLeverage}x-{maxLeverage}x, close with {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 5,
    max_pnl_percent: null,
    min_leverage: 5,
    max_leverage: 15,
    max_duration_minutes: 120,
    min_position_size_usd: 250,
    ttl_minutes: 480,
    reward_points: 450,
  },
  {
    id: "r-btc-sniper",
    tier: "rare",
    weight: 4,
    titleTemplate: "Sniper: {asset}",
    descriptionTemplate:
      "Hit {minPnl}%+ profit on {asset} at {minLeverage}x+ leverage inside {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 2,
    max_pnl_percent: null,
    min_leverage: 15,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 250,
    ttl_minutes: 480,
    reward_points: 400,
  },
  {
    id: "r-bonk-breakout",
    tier: "rare",
    weight: 4,
    titleTemplate: "Breakout: {asset}",
    descriptionTemplate:
      "Catch a {asset} breakout at {minLeverage}x+ leverage and close with {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 5,
    max_pnl_percent: null,
    min_leverage: 10,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 100,
    ttl_minutes: 360,
    reward_points: 500,
  },
  {
    id: "r-sol-ladder",
    tier: "rare",
    weight: 4,
    titleTemplate: "Leverage ladder: {asset}",
    descriptionTemplate:
      "{asset} at {minLeverage}x-{maxLeverage}x leverage, {minPnl}%+ profit, {maxDuration}-minute window.",
    asset: "SOL",
    direction: null,
    min_pnl_percent: 3,
    max_pnl_percent: null,
    min_leverage: 3,
    max_leverage: 8,
    max_duration_minutes: 120,
    min_position_size_usd: 150,
    ttl_minutes: 480,
    reward_points: 250,
  },
  {
    id: "r-btc-reversal",
    tier: "rare",
    weight: 4,
    titleTemplate: "Reversal: {asset}",
    descriptionTemplate:
      "Long {asset} at {minLeverage}x+ leverage, close at {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "BTC",
    direction: "LONG",
    min_pnl_percent: 3,
    max_pnl_percent: null,
    min_leverage: 5,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 200,
    ttl_minutes: 360,
    reward_points: 300,
  },

  // ─────────────────── Legendary (weight 1 each) ───────────────────
  {
    id: "l-sol-precision-strike",
    tier: "legendary",
    weight: 1,
    titleTemplate: "Precision strike: {asset}",
    descriptionTemplate:
      "Open a {asset} long at exactly {minLeverage}x-{maxLeverage}x and close in the {minPnl}-{maxPnl}% profit band within {maxDuration} minutes.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 5,
    max_pnl_percent: 10,
    min_leverage: 5,
    max_leverage: 10,
    max_duration_minutes: 60,
    min_position_size_usd: 500,
    ttl_minutes: 720,
    reward_points: 2000,
  },
  {
    id: "l-btc-degen-50x",
    tier: "legendary",
    weight: 1,
    titleTemplate: "Degen 50x: {asset}",
    descriptionTemplate:
      "Survive {asset} at {minLeverage}x+ leverage and close with {minPnl}%+ profit in {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 5,
    max_pnl_percent: null,
    min_leverage: 50,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 500,
    ttl_minutes: 1440,
    reward_points: 2500,
  },
  {
    id: "l-bonk-lottery",
    tier: "legendary",
    weight: 1,
    titleTemplate: "Lottery ticket: {asset}",
    descriptionTemplate:
      "{asset} at {minLeverage}x+ leverage, {minPnl}%+ profit, {maxDuration}-minute window. Survivors only.",
    asset: "BONK",
    direction: null,
    min_pnl_percent: 10,
    max_pnl_percent: null,
    min_leverage: 20,
    max_leverage: null,
    max_duration_minutes: 30,
    min_position_size_usd: 200,
    ttl_minutes: 720,
    reward_points: 1500,
  },
  {
    id: "l-sol-hyper",
    tier: "legendary",
    weight: 1,
    titleTemplate: "Hyper long: {asset}",
    descriptionTemplate:
      "{asset} long at {minLeverage}x+ leverage, hit {minPnl}%+ profit inside {maxDuration} minutes.",
    asset: "SOL",
    direction: "LONG",
    min_pnl_percent: 8,
    max_pnl_percent: null,
    min_leverage: 20,
    max_leverage: null,
    max_duration_minutes: 60,
    min_position_size_usd: 500,
    ttl_minutes: 1440,
    reward_points: 2500,
  },
  {
    id: "l-btc-titan",
    tier: "legendary",
    weight: 1,
    titleTemplate: "Titan: {asset}",
    descriptionTemplate:
      "{asset} at {minLeverage}x-{maxLeverage}x leverage, close in the {minPnl}-{maxPnl}% band within {maxDuration} minutes.",
    asset: "BTC",
    direction: null,
    min_pnl_percent: 5,
    max_pnl_percent: 15,
    min_leverage: 20,
    max_leverage: 50,
    max_duration_minutes: 120,
    min_position_size_usd: 500,
    ttl_minutes: 1440,
    reward_points: 2200,
  },
];
